### ISSUE TITLE
Parcels can be created with non-null fields set to null

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/decentraland-subgraph#18]
We don't always succeed at parsing the CSV, and then we ignore a `LandUpdate`.  But there are events where we update a Parcel, but we don't check if it actually exists already so if the `LandUpdate` was ignored we end up creating an incomplete Parcel without some of the non-nullable fields.

**Comment by Jannis** [comment]
Ah, ok, let me see about that.

**Comment by Jannis** [comment]
Yep, that resolves it.
